import type { HydrogenStation } from '@/types';

// Global hydrogen refueling stations — static GeoJSON seed
// Sources: H2Stations.org, IEA Hydrogen TCP, individual operator disclosures
// Updated: 2026-07
export const HYDROGEN_STATIONS: HydrogenStation[] = [
  // ── Japan ────────────────────────────────────────────────────────────
  {
    id: 'h2-001',
    name: 'Tokyo Shibaura HRS',
    city: 'Tokyo',
    country: 'Japan',
    lat: 35.6762,
    lon: 139.6503,
    status: 'operational',
    capacityKgPerDay: 300,
    operator: 'Iwatani',
  },
  {
    id: 'h2-002',
    name: 'Tokyo Ariake HRS',
    city: 'Tokyo',
    country: 'Japan',
    lat: 35.6342,
    lon: 139.7932,
    status: 'operational',
    capacityKgPerDay: 200,
    operator: 'ENEOS',
  },
  {
    id: 'h2-003',
    name: 'Yokohama Asahi HRS',
    city: 'Yokohama',
    country: 'Japan',
    lat: 35.4437,
    lon: 139.6380,
    status: 'operational',
    capacityKgPerDay: 150,
    operator: 'JXTG',
  },
  {
    id: 'h2-004',
    name: 'Nagoya Midori HRS',
    city: 'Nagoya',
    country: 'Japan',
    lat: 35.1815,
    lon: 136.9066,
    status: 'operational',
    capacityKgPerDay: 250,
    operator: 'Taiyo Nippon Sanso',
  },
  {
    id: 'h2-005',
    name: 'Osaka Konohana HRS',
    city: 'Osaka',
    country: 'Japan',
    lat: 34.6937,
    lon: 135.5023,
    status: 'operational',
    capacityKgPerDay: 200,
    operator: 'Iwatani',
  },
  // ── South Korea ──────────────────────────────────────────────────────
  {
    id: 'h2-006',
    name: 'Seoul Sangam HRS',
    city: 'Seoul',
    country: 'South Korea',
    lat: 37.5665,
    lon: 126.9780,
    status: 'operational',
    capacityKgPerDay: 250,
    operator: 'Hyundai / SK E&S',
  },
  {
    id: 'h2-007',
    name: 'Incheon Cheongna HRS',
    city: 'Incheon',
    country: 'South Korea',
    lat: 37.4563,
    lon: 126.7052,
    status: 'operational',
    capacityKgPerDay: 300,
    operator: 'Hyundai / SK E&S',
  },
  {
    id: 'h2-008',
    name: 'Ulsan Buk-gu HRS',
    city: 'Ulsan',
    country: 'South Korea',
    lat: 35.5384,
    lon: 129.3114,
    status: 'operational',
    capacityKgPerDay: 500,
    operator: 'Hyundai / SK E&S',
  },
  {
    id: 'h2-009',
    name: 'Changwon Seongsan HRS',
    city: 'Changwon',
    country: 'South Korea',
    lat: 35.2279,
    lon: 128.6818,
    status: 'operational',
    capacityKgPerDay: 200,
    operator: 'Hyundai',
  },
  // ── Germany ──────────────────────────────────────────────────────────
  {
    id: 'h2-010',
    name: 'Stuttgart HRS',
    city: 'Stuttgart',
    country: 'Germany',
    lat: 48.7758,
    lon: 9.1829,
    status: 'operational',
    capacityKgPerDay: 200,
    operator: 'H2 MOBILITY',
  },
  {
    id: 'h2-011',
    name: 'Berlin Spandau HRS',
    city: 'Berlin',
    country: 'Germany',
    lat: 52.5200,
    lon: 13.4050,
    status: 'operational',
    capacityKgPerDay: 200,
    operator: 'H2 MOBILITY',
  },
  {
    id: 'h2-012',
    name: 'Munich Frankfurter Ring HRS',
    city: 'Munich',
    country: 'Germany',
    lat: 48.1351,
    lon: 11.5820,
    status: 'operational',
    capacityKgPerDay: 250,
    operator: 'H2 MOBILITY',
  },
  {
    id: 'h2-013',
    name: 'Hamburg HafenCity HRS',
    city: 'Hamburg',
    country: 'Germany',
    lat: 53.5511,
    lon: 9.9937,
    status: 'operational',
    capacityKgPerDay: 200,
    operator: 'H2 MOBILITY',
  },
  {
    id: 'h2-014',
    name: 'Frankfurt Höchst HRS',
    city: 'Frankfurt',
    country: 'Germany',
    lat: 50.1109,
    lon: 8.6821,
    status: 'operational',
    capacityKgPerDay: 200,
    operator: 'H2 MOBILITY',
  },
  // ── California, USA ──────────────────────────────────────────────────
  {
    id: 'h2-015',
    name: 'Los Angeles Harbor City HRS',
    city: 'Los Angeles',
    country: 'USA',
    lat: 33.9425,
    lon: -118.4081,
    status: 'operational',
    capacityKgPerDay: 350,
    operator: 'True Zero / FirstElement',
  },
  {
    id: 'h2-016',
    name: 'San Francisco Mission HRS',
    city: 'San Francisco',
    country: 'USA',
    lat: 37.7749,
    lon: -122.4194,
    status: 'operational',
    capacityKgPerDay: 200,
    operator: 'True Zero / FirstElement',
  },
  {
    id: 'h2-017',
    name: 'San Jose Brokaw HRS',
    city: 'San Jose',
    country: 'USA',
    lat: 37.3382,
    lon: -121.8863,
    status: 'operational',
    capacityKgPerDay: 200,
    operator: 'True Zero / FirstElement',
  },
  {
    id: 'h2-018',
    name: 'Sacramento HRS',
    city: 'Sacramento',
    country: 'USA',
    lat: 38.5816,
    lon: -121.4944,
    status: 'operational',
    capacityKgPerDay: 180,
    operator: 'True Zero / FirstElement',
  },
  {
    id: 'h2-019',
    name: 'Irvine HRS',
    city: 'Irvine',
    country: 'USA',
    lat: 33.6846,
    lon: -117.8265,
    status: 'operational',
    capacityKgPerDay: 200,
    operator: 'True Zero / FirstElement',
  },
  // ── China ────────────────────────────────────────────────────────────
  {
    id: 'h2-020',
    name: 'Shanghai Anting HRS',
    city: 'Shanghai',
    country: 'China',
    lat: 31.2304,
    lon: 121.4737,
    status: 'operational',
    capacityKgPerDay: 500,
    operator: 'Sinopec / SAIC',
  },
  {
    id: 'h2-021',
    name: 'Beijing Daxing HRS',
    city: 'Beijing',
    country: 'China',
    lat: 39.9042,
    lon: 116.4074,
    status: 'operational',
    capacityKgPerDay: 400,
    operator: 'Sinopec',
  },
  {
    id: 'h2-022',
    name: 'Guangzhou Nansha HRS',
    city: 'Guangzhou',
    country: 'China',
    lat: 23.1291,
    lon: 113.2644,
    status: 'operational',
    capacityKgPerDay: 300,
    operator: 'Sinopec',
  },
  // ── Taiwan ───────────────────────────────────────────────────────────
  {
    id: 'h2-023',
    name: 'Taipei Neihu HRS',
    city: 'Taipei',
    country: 'Taiwan',
    lat: 25.0330,
    lon: 121.5654,
    status: 'planned',
    capacityKgPerDay: 200,
    operator: 'CPC Taiwan',
  },
  // ── France ───────────────────────────────────────────────────────────
  {
    id: 'h2-024',
    name: 'Paris Pont de Sèvres HRS',
    city: 'Paris',
    country: 'France',
    lat: 48.8566,
    lon: 2.3522,
    status: 'operational',
    capacityKgPerDay: 200,
    operator: 'Air Liquide / HysetCo',
  },
  {
    id: 'h2-025',
    name: 'Lyon A7 HRS',
    city: 'Lyon',
    country: 'France',
    lat: 45.7640,
    lon: 4.8357,
    status: 'operational',
    capacityKgPerDay: 150,
    operator: 'Air Liquide',
  },
  // ── Netherlands ──────────────────────────────────────────────────────
  {
    id: 'h2-026',
    name: 'Amsterdam Westpoort HRS',
    city: 'Amsterdam',
    country: 'Netherlands',
    lat: 52.3676,
    lon: 4.9041,
    status: 'operational',
    capacityKgPerDay: 250,
    operator: 'Shell / WaterstofNet',
  },
  {
    id: 'h2-027',
    name: 'Rotterdam Pernis HRS',
    city: 'Rotterdam',
    country: 'Netherlands',
    lat: 51.9244,
    lon: 4.4777,
    status: 'operational',
    capacityKgPerDay: 400,
    operator: 'Air Liquide',
  },
  // ── Switzerland ──────────────────────────────────────────────────────
  {
    id: 'h2-028',
    name: 'Zürich Hunzenschwil HRS',
    city: 'Zürich',
    country: 'Switzerland',
    lat: 47.3769,
    lon: 8.5417,
    status: 'operational',
    capacityKgPerDay: 150,
    operator: 'H2Energy / Coop',
  },
  // ── UK ───────────────────────────────────────────────────────────────
  {
    id: 'h2-029',
    name: 'London Heathrow HRS',
    city: 'London',
    country: 'UK',
    lat: 51.5074,
    lon: -0.1278,
    status: 'operational',
    capacityKgPerDay: 200,
    operator: 'Air Products / ITM Power',
  },
  // ── Australia ────────────────────────────────────────────────────────
  {
    id: 'h2-030',
    name: 'Melbourne Clayton HRS',
    city: 'Melbourne',
    country: 'Australia',
    lat: -37.8136,
    lon: 144.9631,
    status: 'planned',
    capacityKgPerDay: 150,
    operator: 'CSIRO / Toyota',
  },
];
